version: '3.8'
services:

  backend:
    build: ./movie-booking-backend
    container_name: movie-booking-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # MongoDB Configuration
      - SPRING_DATA_MONGODB_URI=mongodb+srv://root:admin@movie-app.ukcpt9y.mongodb.net
      - SPRING_DATA_MONGODB_DATABASE=moviebooking
      
      # JWT Configuration
      - JWT_SECRET=fa6c66042f6370cf853844434a6a3050842bfbf2fd91620436c81ea23364d5ea
      - JWT_EXPIRATION=86400000
      
      # Server Configuration
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
      
      # Logging Configuration
      - LOGGING_LEVEL_COM_MOVIEBOOKING=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB=DEBUG
      
      # Jackson Configuration
      - SPRING_JACKSON_DATE_FORMAT=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
      - SPRING_JACKSON_TIME_ZONE=UTC
    

  frontend:
    build:
      context: ./movie-booking-frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:8080
        REACT_APP_API_BASE: /api
        REACT_APP_APP_NAME: Movie Booking App
        REACT_APP_VERSION: 1.0.0
        REACT_APP_ENABLE_DEBUG: "true"
        REACT_APP_ENABLE_ANALYTICS: "false"
    container_name: movie-booking-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      # Backend API Configuration
      - REACT_APP_BACKEND_URL=http://3.110.41.24:8080
      - REACT_APP_API_BASE=/api
      
      # Application Configuration
      - REACT_APP_APP_NAME=Movie Booking App
      - REACT_APP_VERSION=1.0.0
      
      # Feature Flags
      - REACT_APP_ENABLE_DEBUG=true
      - REACT_APP_ENABLE_ANALYTICS=false
    depends_on:
      - backend

