# Production Profile Configuration
# This profile is activated when SPRING_PROFILES_ACTIVE=prod

spring:
  data:
    mongodb:
      # Production MongoDB configuration
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE:moviebooking}
  
  # Production Jackson configuration
  jackson:
    date-format: ${SPRING_JACKSON_DATE_FORMAT:yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}
    time-zone: ${SPRING_JACKSON_TIME_ZONE:UTC}

# Production JWT configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# Production logging configuration
logging:
  level:
    com.moviebooking: ${LOGGING_LEVEL_COM_MOVIEBOOKING:WARN}
    org.springframework.data.mongodb: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB:WARN}
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"

# Production server configuration
server:
  port: ${SERVER_PORT:8080}
  # Enable compression for better performance
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  # Security headers
  servlet:
    session:
      timeout: 30m

# Production management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false

# Production security configuration
security:
  require-ssl: true 