# Docker Profile Configuration
# This profile is activated when SPRING_PROFILES_ACTIVE=docker

spring:
  data:
    mongodb:
      # Docker-specific MongoDB configuration
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo:27017/moviebooking}
      database: ${SPRING_DATA_MONGODB_DATABASE:moviebooking}
  
  # Docker-specific Jackson configuration
  jackson:
    date-format: ${SPRING_JACKSON_DATE_FORMAT:yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}
    time-zone: ${SPRING_JACKSON_TIME_ZONE:UTC}

# Docker-specific JWT configuration
jwt:
  secret: ${JWT_SECRET:fa6c66042f6370cf853844434a6a3050842bfbf2fd91620436c81ea23364d5ea}
  expiration: ${JWT_EXPIRATION:86400000}

# Docker-specific logging configuration
logging:
  level:
    com.moviebooking: ${LOGGING_LEVEL_COM_MOVIEBOOKING:INFO}
    org.springframework.data.mongodb: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"

# Docker-specific server configuration
server:
  port: ${SERVER_PORT:8080}
  # Enable compression for better performance
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Docker-specific management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized 