server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:admin@localhost:27017/?authSource=admin}
      database: ${SPRING_DATA_MONGODB_DATABASE:moviebooking}
  
  jackson:
    default-property-inclusion: NON_NULL
    date-format: ${SPRING_JACKSON_DATE_FORMAT:yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}
    time-zone: ${SPRING_JACKSON_TIME_ZONE:UTC}

jwt:
  secret: ${JWT_SECRET:fa6c66042f6370cf853844434a6a3050842bfbf2fd91620436c81ea23364d5ea}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

logging:
  level:
    com.moviebooking: ${LOGGING_LEVEL_COM_MOVIEBOOKING:INFO}
    org.springframework.data.mongodb: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"

# SpringDoc OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.moviebooking.controller
  paths-to-match: /api/**